# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: rootly
output: schema.gen.go
generate:
  models: true
  client: true
  embedded-spec: true
output-options:
  # make sure that we generate /all/ types, regardless of whether they're used by our API Client or not
  skip-prune: true
